name: Update types
on:
  schedule:
    - cron: '0 0 * * 1'
    - cron: '0 0 * * 3'
    - cron: '0 0 * * 5'
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
      - name: Update types
        run: npm run start
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            dist
            package.json
          author_name: Defkil
          author_email: dev@olivergruettner.de
          message: 'bot: Update types and package version'
